### ISSUE TITLE
Duplicate module name

### ISSUE THREAD

**Issue by bailih** [indiespirit/react-native-chart-kit#1]
After I install the package and start the project, I got several error messages like: 

jest-haste-map: @providesModule naming collision:
  Duplicate module name: CheckBox
  Paths: .../node_modules/react-native-scrollable-tab-view/node_modules/react-native/Libraries/Components/CheckBox/CheckBox.ios.js collides with .../node_modules/react-native-chart-kit/node_modules/react-native/Libraries/Components/CheckBox/CheckBox.ios.js

This warning is caused by a @providesModule declaration with the same name across two different files.
***ERROR STARTING PACKAGER***

I am using 
`"expo": "^22.0.0",
    "npm": "^5.6.0",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-native": "^0.49.5",`

**Comment by xTMNTxRaphaelx** [comment]
I has this same error too. :(

**Comment by N1ghtly** [comment]
Any progress on this? The library looks sick but I'm getting a lot of naming collisions.

**Comment by Hermanya** [comment]
I published new version, I moved react-native to dev and peer dependencies.
