### ISSUE TITLE
undefined is not an object (evaluating 'this.props.style.borderRadius')

### ISSUE THREAD

**Issue by EnesIdrisoglu** [indiespirit/react-native-chart-kit#10]
I try to make ContributionGraph, and i'm taking this error : **TypeError: undefined is not an object (evaluating 'this.props.style.borderRadius')**

here is relevant part of my code 

`

    render() {
    const chartConfig = {
      backgroundGradientFrom: '#1E2923',
      backgroundGradientTo: '#08130D',
      color: (opacity = 1) => 'rgba(26, 255, 146, ${opacity})'      
    }
    
    const screenWidth = Dimensions.get('window').width
    const commitsData = [
      { date: '2017-01-02', count: 1 },
      { date: '2017-01-03', count: 2 },
      { date: '2017-01-04', count: 3 },
      { date: '2017-01-05', count: 4 },
      { date: '2017-01-06', count: 5 },
      { date: '2017-01-30', count: 2 },
      { date: '2017-01-31', count: 3 },
      { date: '2017-03-01', count: 2 },
      { date: '2017-04-02', count: 4 },
      { date: '2017-03-05', count: 2 },
      { date: '2017-02-30', count: 4 }
    ]
    
    if(this.state.loading){
      return(
      <View style={styles.container}>
        <ActivityIndicator size="large"/>
      </View>
      )
    }
    return (

      <View style={styles.container}>
        <ContributionGraph
          values={commitsData}
          endDate={new Date('2017-04-01')}
          numDays={105}
          width={screenWidth}
          height={220}
          chartConfig={chartConfig}
        />
      </View>
      
    );
    }
  
    }`

**Comment by dverma4u** [comment]
Hello, there is a little mistake i think
Solution: 
 open you_app_name\node_modules\react-native-chart-kit\src\contribution-graph.js
and replace this.props.style.borderRadius with this.props.chartConfig.style.borderRadius in <Rect />

your render method will look like
`render() {
    return (
      <View style={this.props.style || {}}>
        <Svg height={this.props.height} width={this.props.width}>
          {this.renderDefs({
            width: this.props.width,
            height: this.props.height,
            ...this.props.chartConfig
          })}
          <Rect
            width="100%"
            height={this.props.height}
            rx={this.props.chartConfig.style.borderRadius}
            ry={this.props.chartConfig.style.borderRadius}
            fill="url(#backgroundGradient)"
          />
          <G>{this.renderMonthLabels()}</G>
          <G>{this.renderAllWeeks()}</G>
        </Svg>
      </View>
    );
  }
}`

**Comment by olegberman** [comment]
Can you make a PR @dverma4u ? Thank you

**Comment by olegberman** [comment]
#11

**Comment by Hermanya** [comment]
thanks again @dverma4u, closing this issue

**Comment by Mirazim123** [comment]
Thank you 👍
