### ISSUE TITLE
APP crash when build for Production and proguard is enabled

### ISSUE THREAD

**Issue by P21Marcelo** [indiespirit/react-native-chart-kit#115]
when i build a android release it crashes with the following error message:

```
java.lang.IllegalStateException: 
  at com.horcrux.svg.t.a (Unknown Source:92)

Caused by: java.lang.NoSuchFieldException: 
  at java.lang.Class.getField (Class.java:1601)
  at com.horcrux.svg.t.a (Unknown Source:55)

```
that just happens when its build with proguard enabled.i know its related with react-native-svg, but since i just have it as support for line chars...
any guidance? thanks in advanced.

**Comment by fadak0828** [comment]
Try adding 
`-keep public class com.horcrux.svg.** {*;} `
in your {projectRoot}/android/app/proguard-rules.pro
It was work for me

**Comment by NitayRabi** [comment]
Hey! @fadak0828, this seems to happen with expo apps (even not in production mode) - any solution for expo users?

**Comment by BiplovQss** [comment]
> Try adding
> `-keep public class com.horcrux.svg.** {*;} `
> in your {projectRoot}/android/app/proguard-rules.pro
> It was worked for me

thanks. It helped

**Comment by ammarbror** [comment]
> Try adding
> `-keep public class com.horcrux.svg.** {*;} `
> in your {projectRoot}/android/app/proguard-rules.pro
> It was worked for me

Thanks

**Comment by uzair555** [comment]
> Try adding `-keep public class com.horcrux.svg.** {*;} ` in your {projectRoot}/android/app/proguard-rules.pro It was worked for me

its not working

**Comment by flav1o** [comment]
>
Took me 2 days to solve this, thank you so much. 
god bless you
