### ISSUE TITLE
[question]how do i use this charts with tsx(typescript)?

### ISSUE THREAD

**Issue by hirasaki1985** [indiespirit/react-native-chart-kit#119]
I want to use this libraries with typescript.
but I can't find declaration file.(@types file or ~~.d.ts)

Are you planning to create a types file in the future?

**Comment by Hermanya** [comment]
This is a great idea, but I haven't had time to do this. I'd welcome a PR.

**Comment by hirasaki1985** [comment]
I tried to make index.d.ts file.
please check PR.

I don't know each chart detailed specifications.
please check each chart props.

I have confirmed that each sample in README.md works in my local environment on tsx file.

**Comment by Hermanya** [comment]
Addressed in https://github.com/indiespirit/react-native-chart-kit/pull/120
