### ISSUE TITLE
How to draw a chart exactly like this??/

### ISSUE THREAD

**Issue by MohithHasan** [indiespirit/react-native-chart-kit#12]
![screen shot 2018-05-11 at 12 54 36 pm](https://user-images.githubusercontent.com/34531234/39922227-ef63beba-553f-11e8-9e3a-650101d45ffd.png)

**Comment by MohithHasan** [comment]
i want to start bezier chart from 6:00, but by default it starts from 0:00
![screen shot 2018-05-14 at 11 27 40 am](https://user-images.githubusercontent.com/34531234/39979615-77986116-5769-11e8-9b73-01873b9cfc0a.png)

**Comment by yogeshR5** [comment]
@MohithHasan 
how to remove background grid that doted lines

**Comment by Hermanya** [comment]
you would have to create a custom graph for this

**Comment by Myzel394** [comment]
@Hermanya how do we create custom graphs?
