### ISSUE TITLE
How to change the color of the shadow separately from the line and text(LineChart)

### ISSUE THREAD

**Issue by young-4ever-young** [indiespirit/react-native-chart-kit#128]

**Comment by young-4ever-young** [comment]
How to change the color of the shadow separately from the line and text(LineChart)
![Simulator Screen Shot - iPhone X - 2019-06-28 at 13 37 45](https://user-images.githubusercontent.com/38099684/60336912-502b0f00-99aa-11e9-971b-2e0d5f74fb84.png)

**Comment by Andropogon** [comment]
Hi have you solve this problem?
