### ISSUE TITLE
How do I remove the extra space on the right side on line charts?

### ISSUE THREAD

**Issue by hefejeff** [indiespirit/react-native-chart-kit#134]
<img width="324" alt="Screen Shot 2019-07-15 at 07 25 41" src="https://user-images.githubusercontent.com/9152006/61219684-f88ee200-a6d1-11e9-8951-157fdeae8e3f.png">

It seems that there is an extra value at the end but my label and data arrays match?

**Comment by rishab1065** [comment]
@Hermanya Any updates on this issue?

**Comment by Hermanya** [comment]
Unfortunately, no updates. But I would welcome a PR.

**Comment by rishab1065** [comment]
I have rasied a PR for the same. Please verify https://github.com/indiespirit/react-native-chart-kit/pull/189

**Comment by Hermanya** [comment]
#189 is merged
