### ISSUE TITLE
ADD TEXT CONTENT INSIDE LINE CHART CONNECTING DOTS 

### ISSUE THREAD

**Issue by chetna-webonise** [indiespirit/react-native-chart-kit#139]
Is there any way to add DATA to the dots connecting the line chart.

![image](https://user-images.githubusercontent.com/47411313/62150272-28b5c200-b31b-11e9-87f9-b1f8872377c3.png)

Like this

**Comment by Hermanya** [comment]
this is currently not supported

**Comment by chetna-webonise** [comment]
ok no worries. I have managed the same view using **react-native-svg** with charts.
Thanks!!
