### ISSUE TITLE
Can I change Inner dash lines to solid Inner lines? 

### ISSUE THREAD

**Issue by SyedShahbazHussain** [indiespirit/react-native-chart-kit#145]
I want to change the inner dash lines to inner solid lines.....

**Comment by danipralea** [comment]
```propsForBackgroundLines: {
            strokeDasharray: "" // solid background lines with no dashes
          }```

**Comment by AurangsEmpire** [comment]
> ```js
> propsForBackgroundLines: {
>      strokeDasharray: "" // solid background lines with no dashes
> }
> ```

Worked!!! Thanks :)

**Comment by conor909** [comment]
Where do I find the available props for `propsForBackgroundLines` - and for this library in general.  Documentation seems a lacking

**Comment by SyedShahbazHussain** [comment]
> ```js
> propsForBackgroundLines: {
>      strokeDasharray: "" // solid background lines with no dashes
> }
> ```

**Comment by SyedShahbazHussain** [comment]
> ```js
> propsForBackgroundLines: {
>      strokeDasharray: "" // solid background lines with no dashes
> }
> ```

Thanks <3

**Comment by 1mehdifaraji** [comment]
@conor909 You can find the available props from [react native svg line documentation](https://github.com/react-native-svg/react-native-svg#line) all the props that the Line component accept , it can be used in propsForBackgroundLines .

**Comment by anfishka** [comment]
thanks a lot
