### ISSUE TITLE
If values are same on the line chart then please return the index of this in data-set, so that actual values and their corresponding details can be get from this

### ISSUE THREAD

**Issue by MD1990** [indiespirit/react-native-chart-kit#150]
Can you also return index with the data point click method in the line chart as I am facing a tool tip next to the data point and if values are same I am not able to get accurate index of the data point and find object with different properties but same values. Please let me know if I can create a pull request for same.

**Comment by MD1990** [comment]
I have created a pull request : https://github.com/indiespirit/react-native-chart-kit/pull/151/commits/401f76953d7cce0c4081b40590612d914f178a40 please review

**Comment by vitorverasm** [comment]
With #151 this is available on v3.3.0 and can be closed.
