### ISSUE TITLE
Different line color and label color for LineChart component

### ISSUE THREAD

**Issue by slavkobojanic** [indiespirit/react-native-chart-kit#153]
Just wondering if there was some way to have them be two separate colors rather than the same? Would be a nice addition to have if not.

**Comment by Hermanya** [comment]
This is not supported right now, but it could be a nice addition.

**Comment by LaszloLango** [comment]
+1 I also need this feature. :)

**Comment by slavkobojanic** [comment]
I'm gonna have a go at implementing the colored labels feature, will get back to you if I manage!

**Comment by slavkobojanic** [comment]
![image](https://user-images.githubusercontent.com/914906/65034634-c6785580-d98a-11e9-9135-2986ab450ecb.png)

Funnily enough, I was able to get differently label colors working by adding an extra prop into the chartConfig and then setting the fill value for the `<Text>` elements to that prop inside of the AbstractChart element since all the charts extend off AbstractChart.
