### ISSUE TITLE
X-axis labels overlapping

### ISSUE THREAD

**Issue by bhoomika911** [indiespirit/react-native-chart-kit#155]
@indiespirit, I would like to thank for this great repo.

My issue is that x-axis labels are over lapping if text is large as per attachment.

![image](https://user-images.githubusercontent.com/26411261/64487816-e73efd80-d25c-11e9-9ff3-067e32935bf5.png)

How can we fix this?

**Comment by JaredDahlke** [comment]
+1 I am also having this problem. How can we make the x axis labels vertical or at least angled so more stuff fits?

**Comment by handoff** [comment]
Yes, something like this https://c3js.org/samples/axes_x_tick_rotate.html

**Comment by bhoomika911** [comment]
Hello guys,

Anyone can please help on this?

**Comment by JaredDahlke** [comment]
if someone can point me in the right direction I will try to fork it. Anybody? We need vertical x labels

**Comment by Hermanya** [comment]
@JaredDahlke  There is a contribution guide, PRs are welcome https://github.com/indiespirit/react-native-chart-kit/blob/master/contributing.md

**Comment by JaredDahlke** [comment]
@Hermanya ,
Within line-chart.js there is a function called `renderHorizontalLabels` .
It receives the following inputs:
config
count
data
paddingTop
paddingRight

To start off, I tried to find what file that function is in but could not find it. Could you point me in the right direction?

**Comment by bhoomika911** [comment]
@JaredDahlke, you can find that "renderHorizontalLabels" function in this path **"REact-native-chart-kit/src/abstract-chart.js"**

**Comment by JaredDahlke** [comment]
Thank you. Looks like that function just renders a text component. I’m going to try to use transform: [{ rotate: '90deg'}] on it when I get to my computer

**Comment by JaredDahlke** [comment]
ok I spent a couple hours trying to get this to work, I failed to get it to work. Here's what I found out:
1. the function that renders the x axis labels is oddly called 'renderVerticalLabels' in abstract-chart.js
2. It maps through the label data passed to it and creates a text component for each one
3. I tried using transform on the text component to rotate
4. I tried wrapping the text component in a view and applying the rotation to the view
5. I tried wrapping the text component in a react-native-svg Rect component and rotating the Rect
6. I tried Animated from 'react-native'

All of the above just resulted in the x axis labels simply dissapearing. Anybody else have a chance to give it a shot? Any pointers? Kinda new to this.

**Comment by bhoomika911** [comment]
@Hermanya, why is this issue closed?

If any one found solution for this,  just let me know. I am still facing issue.

**Comment by Hermanya** [comment]
I just merged https://github.com/indiespirit/react-native-chart-kit/pull/164, which adds label rotation to LineChart using `horizontalLabelRotation` and `verticalLabelRotation` props.

I did not realize this issue is about the BarChart, reopening the issue. The solution should be  simliar to the one in that PR.

**Comment by stephenc222** [comment]
I created PR #166 to address this issue for bar charts. Happy to have feedback!

**Comment by Hermanya** [comment]
You can now add `verticalLabelRotation={30}` prop to a BarChart

**Comment by nychinn** [comment]
When I tried adding verticalLabelRotation={30} to my LineChart, it rotated the whole group of labels rather than the individual label itself (so it ended up disappearing off the chart). What could I be doing wrong?

**Comment by Maskedman99** [comment]
For anyone referring this issue, If your data set is larger that even after rotating by 90 degree labels overlap, then you can use ```hidePointsAtIndex``` prop.

**Comment by nikTC** [comment]
For large data sets, simply can add, can't find any solution for 100's of data points in this library, but can be done with the following workaround. If anyone has a better approach plz let us all know.:

<ScrollView horizontal={true}>
<LineChart
  width={(width * 0.1 )* graph_data_length} // width is screen width we can get it from Dimensions, and 0.1 is 1% of screen into total number of data points this will 
  .
  .

**Comment by tobiyas09** [comment]
Can we put labels in a new line?
![Screenshot 2023-10-24 at 14 26 31](https://github.com/indiespirit/react-native-chart-kit/assets/65284776/436e8444-7102-4616-8a62-c875a8018c72)
I tried to add '\n' in the labels array `['Danielle\nBrown',...]` but it doesn't work, it just adds space.
