### ISSUE TITLE
Line Chart Supports Legend

### ISSUE THREAD

**Issue by SimonPringleWallace** [indiespirit/react-native-chart-kit#158]
With the completion of #37, is it possible to have a legend for a Line Chart? Attempting to add that prop currently doesn't seem to have any effect. I'd be happy to work on a PR for that, if it's a feature of interest.

**Comment by vedmant** [comment]
Yeah, without legend it's not clear which line is which, I need to add custom legend below the chart to describe lines.

**Comment by Lasitha92** [comment]
Any update on this one?

**Comment by SimonPringleWallace** [comment]
Was waiting for a word from the maintainer on whether this would be a welcome addition but it seems like there's enough interest there to merit some work on it. I'll try to work up a PR in the next week or so.

**Comment by SimonPringleWallace** [comment]
Thanks for the thumb Hermanya! To keep with convention, it looks like the legend should run vertically on the right side of the graph. However, most charts that have the legend located there are already relatively compact (progress, stacked-bar, etc) whereas I'd think a legend in that location on a longer line chart might make the chart look compressed. Should I keep the legend to the right side or is having it run vertically across the top of the chart an option?

**Comment by Hermanya** [comment]
Right, it makes sense to render it above or below the chart. Do whatever is better for the app you are building, and we will see what other people think about it if there is any feedback.
