### ISSUE TITLE
react-native-chart-kit

### ISSUE THREAD

**Issue by hamzaalawneh** [indiespirit/react-native-chart-kit#165]
greetings all, i've been working on react-native-chart-kit,specifically on LineChart and i wonder if there is a way that i can change the color of the dots?
also if there is a way to change the color of one dot only that will be really great , here is a  screenshot of the page:

![Screenshot_1569320832](https://user-images.githubusercontent.com/32969060/65510044-937b1800-dedc-11e9-93ab-4e559c6f2693.png)

**Comment by Theokalo** [comment]
In order to change the color of all dots you can add this in your code
`<LineChart 
propsForDots: {
                        r: "6",
                        strokeWidth: "2",
                        stroke: "#3dcd58"
                    } 
/>`

**Comment by vitorverasm** [comment]
This is available in d061a9c and can be closed 👍 .
