### ISSUE TITLE
Possible to add 1 more y-axis (Highest) label?

### ISSUE THREAD

**Issue by leon2835** [indiespirit/react-native-chart-kit#172]
Hi there, e.g the highest data is 350, the bar chart will show the highest y-axis label as 350, is there a possibility to modify 350 into e.g 400 (e.g 0 > 116.67 > 233.33 > 400)? Or append 1 more layer to show 400 (e.g 0 > 116.67 > 233.33 > 350 > 400)? Thank You.
<img width="307" alt="Screenshot 2019-09-30 at 11 53 41" src="https://user-images.githubusercontent.com/19604759/65848609-6ebdef00-e379-11e9-9c7d-feb65cb09c5d.png">

Another question was, currently by default it will automatic generate 4 (y-axis label). Currently Is there anyway to set to 5 or 6 labels & able to define y-axis by ourself?) Thank You

**Comment by aalsa3** [comment]
This would be great.

**Comment by hallanthony** [comment]
Agree, be great to define this, we only need 2 to display, would also be useful to be able to have some method to format the numbers, our customers wants to show thousand separators

**Comment by Hermanya** [comment]
This is not supported, but a Pull Request is welcome. Check out our contribution guide on how to get started.

**Comment by rodolphefauquez** [comment]
Workaround if you just want to add a 'true' max value to your Y labels:
(e.g if you max data value is 350 but you want to show the max label as 400 anyway)

```
 <LineChart
    data={{
      labels: yourXLabels,
      datasets: [
        {
          data: yourMaxYValue, // <=== e.g: [400], the maximum you want, only one value in the array.
          color: () => `rgba(0, 0, 0, 0)` // <=== Here enable transparency of the rgba() to hide the max Y Value dot from your chart.
        },
        {
          data: yourChartValues, // your original data
          color: () => `rgba(255, 144, 182, 1)`
        }
      ]
  }}
/>
```

Preview:
![Screen Shot 2019-10-16 at 17 38 14](https://user-images.githubusercontent.com/9111635/66902524-c461ef00-f03b-11e9-885c-9768ba1b8b5a.png)

But you can't add one more layer or choose yourself you y labels yet.

**Comment by leon2835** [comment]
> Workaround if you just want to add a 'true' max value to your Y labels: just add a fake dataset with a max value.
> 
> e.g if your max data value is 350 but you want to show the max label as 400 anyway
> 
> ```
>  <LineChart
>     data={{
>       labels: yourXLabels,
>       datasets: [
>         {
>           data: yourMaxYValue, // <=== e.g: [400], the maximum you want, only one value in the array.
>           color: () => `rgba(0, 0, 0, 0)` // <=== Here enable transparency of the rgba() to hide the max Y Value dot from your chart.
>         },
>         {
>           data: yourChartValues, // your original data
>           color: () => `rgba(255, 144, 182, 1)`
>         }
>       ]
>   }}
> />
> ```
> 
> Preview:
> ![Screen Shot 2019-10-16 at 17 38 14](https://user-images.githubusercontent.com/9111635/66902524-c461ef00-f03b-11e9-885c-9768ba1b8b5a.png)
> 
> It's just a workaround of course.
> 
> But you can't add one more layer or choose yourself you y labels yet.

I see, it works perfectly although it was a workaround, thanks for it buddy.
