### ISSUE TITLE
bar chart broken in expo 35

### ISSUE THREAD

**Issue by Enalmada** [indiespirit/react-native-chart-kit#176]
Upgrading to Expo 35 appears to make bar charts go blank.

Could you upgrade sample app to the latest expo:
https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

I run "expo upgrade" (followed by "expo install react-native-svg" since that was broken out) and bar charts don't show up.

**Comment by edoantonioco** [comment]
I came here looking for this exact same issue. Latest version of this library doesnt go well with expo 35, in BarChart

**Comment by edoantonioco** [comment]
neither version 3.6.1, which worked before. Maybe its an expo issue.

**Comment by Enalmada** [comment]
@Aleksandern I assume this is a bug with react-native-chart-kit and latest version of react-native-svg?
```
"react-native-svg": "~9.12.0"
```

**Comment by joaovbibiano** [comment]
I having the same problem here... 

Yarn 1.19.1
"expo": "^35.0.0",
"react-native-chart-kit": "^3.13.0",
"react-native-svg": "~9.9.2",
