### ISSUE TITLE
ReferenceError: Can't find variable calcScaler

### ISSUE THREAD

**Issue by AwoyoToyin** [indiespirit/react-native-chart-kit#19]
Following the examples here, I tried creating a LinearChart but get greeted with a 'red screen of death' with this error: ReferenceError: Can't find variable calcScaler.

Any ideas?

**Comment by naldyn** [comment]
The same thing also happens to me, some idea that may be happening?

**Comment by naldyn** [comment]
I found the problem in the code, you should refer to this.calcScaler instead of calcScaler on line-chart.js

**Comment by Thebarda** [comment]
Is there a PR or fork about this issue ?

**Comment by davidmfry** [comment]
I tried changing calcScaler to this.calcScaler but it crashed the app and the app can't even build.

**Comment by davidmfry** [comment]
I made the change and the app crashes.
