### ISSUE TITLE
Invariant Violation: requireNativeComponent: "SNSVGLinearGradient" was not found in the UIManager

### ISSUE THREAD

**Issue by danipralea** [indiespirit/react-native-chart-kit#195]
![Simulator Screen Shot - iPhone X - 2019-10-21 at 12 50 52](https://user-images.githubusercontent.com/768893/67195328-6e0cfb80-f401-11e9-8818-f31c686d145f.png)

Hello! 
I'm wondering if there's any way to fix this. I've tried `link`ing and a bunch of other stuff, I'm honestly left out of ideas.

Any help would be greatly appreciated.

**Comment by n-trance** [comment]
```
// If you don't have SVG
yarn add react-native-svg

// for (RN 0.60+)
cd ios && pod install

// for (RN < 0.60)
react-native link react-native-svg
```
Make sure you close your metro bundler and re-run your application

**Comment by danipralea** [comment]
that's just perfect! thank you so much
