### ISSUE TITLE
Refresh / rerender chart with new props 

### ISSUE THREAD

**Issue by rikinshah23** [indiespirit/react-native-chart-kit#205]
I have 3 options to show Chart data. I load 30 days data to chart - it looks great. 

![image](https://user-images.githubusercontent.com/26806597/67971299-2a20b000-fbd2-11e9-9ecc-9167e74eb1a8.png)

Now if I fetch last 14 days data by selecting a radio button, it updates the props and data is changed now as displayed in chart below. 
And Chart lines are also updated but it still shows old data points from previous draw. 

![image](https://user-images.githubusercontent.com/26806597/67971499-808dee80-fbd2-11e9-9a7e-4970c11d10c3.png)

I need to totally rerender the chart with new data when props changes. 
Can anyone please help?
Thanks

**Comment by Hermanya** [comment]
Try wrapping it in a view and adding the `key` with a value of the radio button. In theory react should discard a component of the key changes. It's a hack, but it's pretty simple.

**Comment by rikinshah23** [comment]
That solved it! Thanks a lot @Hermanya

**Comment by hoangdvAT** [comment]
> Try wrapping it in a view and adding the `key` with a value of the radio button. In theory react should discard a component if the key changes. It's a hack, but it's pretty simple.

You saved my day~~

**Comment by didiraja** [comment]
Still better workaround for refreshing chart data
