### ISSUE TITLE
[Question] Possibility of formatting axis values

### ISSUE THREAD

**Issue by vitorverasm** [indiespirit/react-native-chart-kit#212]
## Description
I'm currently using LinearChart to display a chart with relations:

> Amount of bytes used(Number) X Date(String)

and it's working so far, but I would like to format the label values example:

> 30129195581.44 => 28.06 GB

**Keeping the behavior of the comparison but formatting the output string.** Another lib that I tried had this capability [react-native-svg-charts](https://github.com/JesperLekland/react-native-svg-charts#yaxis), but chart-kit solves many of my problems compared to this other one, so **what is the level of difficulty to add this feature?**

**Edit:**
Of course the formatting function the user will provide.

**Comment by Hermanya** [comment]
It's pretty trivial, and I was advocating to do this in a few PRs, but people prefer prefix/suffix formatting. I'd welcome a PR that adds proper formatting in a non breaking way.

**Comment by vitorverasm** [comment]
Okay, I'll try to do that, trying to maintain the current prefix/suffix capabilities.

**Comment by vitorverasm** [comment]
I did a PR so let's close this and keep the conversation there.
