### ISSUE TITLE
Update typedef for LineChart data object

### ISSUE THREAD

**Issue by Charanor** [indiespirit/react-native-chart-kit#226]
Currently the type definition for the `LineChart` `data` object is just `data: object;` along with a comment describing what props it contains (labels, datasets, etc.). This should be updated to a proper typedefinition. Something like this:

```typescript
interface Dataset {
    data: number[];
    color: (opacity: number) => string;
    strokeWidth: number;
};

interface DataObject {
    labels: string[];
    datasets: Dataset[];
};

data: DataObject;
```

I would create a pull request but I don't know all the props. These are just the ones I found in the documentation.

**Comment by Hermanya** [comment]
This is a great idea
