### ISSUE TITLE
Bezier Style MarginRight Not Working

### ISSUE THREAD

**Issue by Korysam15** [indiespirit/react-native-chart-kit#25]
All, I am trying to center my graph by setting the marginLeft and marginRight to 10. However, marginRight is not working for some reason, marginLeft works but not marginRight. Any suggestions? 

` 
 <ProgressChart
              data={data}
              width={screenWidth}
              height={150}
              chartConfig={{
                backgroundGradientFrom: '#505050',
                backgroundGradientTo: '#707070',
                color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
                style: {
                  borderRadius: 16,
                }
              }}
              bezier
              style={{
                borderRadius: 16,
                marginRight: 10,
                marginLeft: 10
              }}
            />
`
const data = [0.4, 0.6, 0.8]

**Comment by Hermanya** [comment]
Yeah, it's not supported.
If you figure out how to make it work (should be similar to marginLeft), I'd be happy to merge a pull request.

**Comment by Korysam15** [comment]
A workaround I did instead is to make the width equal to the screen width and then subtracted 20 from that. I then just said alignSelf: ‘center’.
