### ISSUE TITLE
RNSVGLinearGradient does not exist

### ISSUE THREAD

**Issue by kashifaliquazi** [indiespirit/react-native-chart-kit#26]
Trying to run quick exampe

`export default class Example extends Component {

  constructor(props){
    super(props);
  }

    render() {
      const data = {
        labels: ['January', 'February', 'March', 'April', 'May', 'June'],
        datasets: [{
          data: [ 20, 45, 28, 80, 99, 43 ]
        }]
      }

        return (
            <View>
          <LineChart
  data={data}
  width={200}
  height={220}
  chartConfig={{
      backgroundColor: '#e26a00',
      backgroundGradientFrom: '#fb8c00',
      backgroundGradientTo: '#ffa726',
      color: (opacity = 1) => `rgba(255, 255, 255, 1)`,
      style: {
        borderRadius: 16
      }
    }}
/>
            </View>
        );
    }
    componentDidMount() {
    
    }
}
`

Enviroment-

    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-chart-kit": "^1.1.5",

getting error 
Invarient Violation : Native component for "RNSVGLinearGradient" does not exist

![screen shot 2018-07-23 at 1 38 37 pm](https://user-images.githubusercontent.com/9718787/43064874-c3de062a-8e7d-11e8-85f0-37234bbc9911.png)

**Comment by Hermanya** [comment]
I think you need to 
```bash
yarn add react-native-svg
react-native link react-native-svg
```
For our testing we use expo, and it comes with react-native-svg out of the box.

**Comment by jmknoll** [comment]
Adding on to @Hermanya 

react-native-svg currently has a bug where automatic linking pulls in libRNSVG-tvOS.a to your Link Binary with Libraries list. Either manually add the project to Xcode, or remove libRNSVG-tvOS after running `react-native link react-native-svg`

See more (here)[https://github.com/react-native-community/react-native-svg/issues/544]

**Comment by noluckjustskill** [comment]
Do not forget **rebuild** your app: `react-native run-android`

**Comment by prasad456** [comment]
All working fine with example app, but while integrating to main project displaying this issues

Not Working for me, I have tried all

after link this was adding in podfile
  pod 'RNSVG', :path => '../node_modules/react-native-svg'


I have installed previously linear-gradient package and installl pods for react-native-crop-image-picker

does this effects on this package?
 please respond me

**Comment by Hermanya** [comment]
I don't think it does, if you could make another example project, more similar to your main project, to reproduce this issue. I could take a look. 

My suspicion is that your main project might have older versions of dependencies.

**Comment by prasad456** [comment]
@Hermanya 

Thanks for the reply, these are my dependencies can you please checkout what are the older versions

`"@expo/vector-icons": "^8.0.0",
    "email-validator": "^2.0.4",
    "moment": "^2.23.0",
    "native-base": "^2.8.1",
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-autocomplete-input": "^3.6.0",
    "react-native-cardview": "^2.0.2",
    "react-native-chart-kit": "^2.0.1",
    "react-native-code-input": "^1.0.6",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^0.19.1",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-linear-gradient": "^2.4.3",
    "react-native-masked-text": "^1.9.2",
    "react-native-pure-chart": "0.0.24",
    "react-native-push-notification": "^3.1.2",
    "react-native-rating": "^2.0.4",
    "react-native-simple-dialogs": "^1.0.0",
    "react-native-simple-toast": "0.0.8",
    "react-native-splash-screen": "^3.1.1",
    "react-native-svg": "^9.0.5",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.17.0"`

**Comment by prasad456** [comment]
I had fixed this issue by removing pods and run react-native link  react-native-svg and then reinstalling the pods for iOS
for Android it works fine from before

**Comment by chuchur-china** [comment]
安装一下 react-native-svg ,然后,手动添加依赖就可以了

**Comment by fabriziobertoglio1987** [comment]
> I think you need to
> 
> ```shell
> yarn add react-native-svg
> react-native link react-native-svg
> ```
> 
> For our testing we use expo, and it comes with react-native-svg out of the box.

yes, maybe that is the problem.. you could mention this in the installation guide. I had to install react-native-svg and I am using xcode

**Comment by Hermanya** [comment]
updated installation instructions
