### ISSUE TITLE
NaN if all data is equal to 0.

### ISSUE THREAD

**Issue by mikerodham** [indiespirit/react-native-chart-kit#27]
In my use case I specifically capture items over the last ten days. If nothing has happened in those ten days the graph will look like this:

![img_36453144ebdf-1](https://user-images.githubusercontent.com/7014362/43195893-42a44772-8ffe-11e8-8d3c-87ff3ba1fb63.png)

As you can see in the bottom left corner it displays `NaN` when it should display `0`.

Here is my data from the server.
```
labels: [],
datasets: [{
  data: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
}]
```

Edit:

Also is there any choice for whole numbers only down the Y axis?

**Comment by Hermanya** [comment]
I'm trying to, but lately I have very little time. Sorry for not getting back to you earlier. This should be an easy fix. Take a look how it renders horizontal labels. You can also take a look at the contribution guide on how to get started.

**Comment by mikerodham** [comment]
That's not a problem, I've been trying to debug as to why it's showing NaN as when I was logging `(((Math.max(...data) - Math.min(...data)) / (count - 1) * i) + Math.min(...data))` I was hit with 0, as expected so I'm not entirely sure whilst it's NaN, when I've got some time I'll look in to this properly and make a PR if necessary.

**Comment by BrightonWeBill** [comment]
The same error occurs when the data is the same number. Has there been a fix for it?
