### ISSUE TITLE
Change color of only one dot in LineChart?

### ISSUE THREAD

**Issue by lentesta** [indiespirit/react-native-chart-kit#295]
I love this package.

Is it possible to change the color of just one dot in a LineChart?  

I'm charting an estimate of how long you'll wait in line at a ride in Walt Disney World, from 8 am to midnight.  I'd like to change the color of the dot that represents the current time, to show the user where they are on the chart.

**Comment by Hermanya** [comment]
There is `getDotColor` it takes the value and the index

**Comment by lentesta** [comment]
How did I miss that?  Thank you!
