### ISSUE TITLE
Customize  values in Y 

### ISSUE THREAD

**Issue by Tatandiaz13** [indiespirit/react-native-chart-kit#30]
Is it possible to add a character in the vertical line?

example:

![captura de pantalla 2018-08-07 a las 21 41 42](https://user-images.githubusercontent.com/19178620/43798588-558c593c-9a8b-11e8-928d-5e84c041b0d9.png)

**Comment by Hermanya** [comment]
Not right now, but it should be relatively easy. I'd gladly accept a PR

**Comment by Manouli** [comment]
@Hermanya is there any plan to sort this out? I could really use this right now.

**Comment by Hermanya** [comment]
Not right now

**Comment by brennedith** [comment]
Hi @Hermanya, just created a pull request related to this.

Regards.

**Comment by vitorverasm** [comment]
With #97 this is solved.
