### ISSUE TITLE
How to keep incomplete array of data from spanning through the whole chart?

### ISSUE THREAD

**Issue by RominHalltari** [indiespirit/react-native-chart-kit#311]
I am having an issue with plotting my data on the `LineChart`. I have days of the month (0 -> 30) on the x axis, and it works great when `data` contains 30 elements. But when it contains 10 items, for example, the line doesn't stop at day 10, but spans even more. I want the line to go up to day 10. Is there any way to do this because this is very common for charts.

**Comment by mertuner** [comment]
Hey did you find a work around for this?

**Comment by rg4real** [comment]
Same.

**Comment by YoshiS214** [comment]
I found a solution.
You can achieve this by adding one more full-size dataset whose opacity is 0 and whose dots are disabled. 
But, you can't use shadow because the shadow of the incomplete line won't match the line self.
