### ISSUE TITLE
Display x-axis value label only every nth item [LineChart]

### ISSUE THREAD

**Issue by murat0** [indiespirit/react-native-chart-kit#360]
Hi all, 

Is there a way to display the **x-axis** value labels only every nth item ? The data will still be available on the graph line but the relative x-axis label would only be shown for some of the graphed data. 

Thank you.

**Comment by dyousufzai** [comment]
I also required this is there any way ?

**Comment by tayloraleach** [comment]
I think I opened the same issue as well. https://github.com/indiespirit/react-native-chart-kit/issues/351 Pretty fundamental requirement that seems to be missing, unfortunately.

**Comment by aboveyunhai** [comment]
This feature already existed in the `<LineChart>`,
`hidePointsAtIndex={ [3, 4] }` will hide the `index 3 and 4` in your graph. 
Apply the logic and create an array for yourself. 
Quick example, `hidePointsAtIndex={ Array.from({length: 5}, (v, k) => (k%2 === 0) ? k : null) }`. This will hide all numbers that can be mod by 2 under 5.

**Comment by tayloraleach** [comment]
Doesn't this just hide the points on the actual graph? Looking to only hide the x labels

**Comment by aboveyunhai** [comment]
> Doesn't this just hide the points on the actual graph? Looking to only hide the x labels

The reason of that is because the `hidePointsAtIndex` is abused similar to `padding` issue. You can simply replace the `hidePointsAtIndex` to `hideLabelsAtLabel` in `abstract-chart.tsx` and then use `hideLabelsAtIndex={ [3, 4] }`. Then they will be handled differently. I lost track of this repo from my own after the typescript rewrote, you can also PR the change with typescript support.

**Comment by mccurrymitchell3** [comment]
If your label values are at regular intervals, you can use this:
`formatXLabel={(value) => value % 2 == 0 ? value : ''}`

If the labels are [0, 1, 2, 3, 4, 5, 6] this will only display 0, 2, 4, 6

**Comment by hamzakashifCL** [comment]
> If your label values are at regular intervals, you can use this: `formatXLabel={(value) => value % 2 == 0 ? value : ''}`
> 
> If the labels are [0, 1, 2, 3, 4, 5, 6] this will only display 0, 2, 4, 6

this works perfect

**Comment by factorycreacom** [comment]
Hello everyone. If you're using a more complex structure, you can do it like this

`formatXLabel={value => chartLabelFormatter(value)}`


```javascript
 const chartLabelFormatter = (value: string) => {
   const index = allHours.indexOf(value);
   return index === 0 || index % 5 === 4 ? value : '';
 };
``` 
   

"Within the chartLabelFormatter function, you can use if-else as you wish. Just make sure you return a value."

**Comment by murat0** [comment]
Ok the replies seem to be offering multiple ways of achieving the task in question. Thank you all for your contribution, I am closing the issue.

**Comment by douglassoldan** [comment]
This works.

```
<LineChart
    data={dataGraph}
    width={screenWidth - 12}
    height={220}
    chartConfig={chartConfig}
    formatXLabel={value => {
      const index = dataGraph.labels.indexOf(value);
      return index % 2 === 0 ? value : '';
    }}
/>
