### ISSUE TITLE
LineChart throws error 'cannot read property color of undefined'

### ISSUE THREAD

**Issue by Clumsy-Coder** [indiespirit/react-native-chart-kit#363]
Using the example provided on [link](https://github.com/indiespirit/react-native-chart-kit#quick-example)

Error is thrown `Cannot read property 'color' of undefined`

![image](https://user-images.githubusercontent.com/19594044/86499581-4a000900-bd49-11ea-8d04-3cff135c8bd9.png)

---
Also using the full code from the example, typescript error is thrown

![image](https://user-images.githubusercontent.com/19594044/86499521-f097da00-bd48-11ea-9b1d-8621ab71f2cc.png)

---
react: 16.11.0
react-native: 0.62.2
react-native-chart-kit: **^6.2.2**
react-native-svg: **^12.1.0**

**Comment by kayotimoteo** [comment]
same problem here

**Comment by Clumsy-Coder** [comment]
This seems to be solved in #375.

Closing issue

**Comment by VasylenckoSlava** [comment]
same problem here
