### ISSUE TITLE
Having different colors for eash data set

### ISSUE THREAD

**Issue by BrightonWeBill** [indiespirit/react-native-chart-kit#37]
So I have two sets of data but they all in one color, I'm trying to have a green color of the first dataset and a red for the other one. How do I go about it?

**Comment by Hermanya** [comment]
For stylistic purposes this is a monochrome lib. But I already accepted on MR, that adds custom colora to the pie chart, see the Readme. 
If you too end up customizing this lib, please create a PR.

**Comment by Zazzzles** [comment]
You can implement this by changing the following lines in `node_modules/react-native-chart-kit/src/line-chart.js`
L:27 = `fill={dataset.svg.fill}`
L:82 = `stroke={dataset.svg.fill}`
L:127 = `stroke={dataset.svg.fill}`

Then pass in multiple lines of data with their colors as follows:
`[
                {
                    data: [ 20, 45, 28, 80, 99, 43 ],
                    svg: {
                        fill: 'rgb(134, 65, 244)',
                    },
                },
                {
                    data: [ 30, 15, 18, 10, 59, 33 ],
                    svg: {
                      fill: 'rgb(234, 80, 144)',
                    },
                },
            ]`

**Comment by AshishCd** [comment]
use Zazzles's example above then follow below
"node_modules/react-native-chart-kit/src/line-chart.js" line 82
const stroke = dataset.svg && dataset.svg.fill;
//line 99
stroke={stroke}

that's all

**Comment by BrightonWeBill** [comment]
Thanks, guys. @iksent, I opened one and im making changes there

**Comment by BrightonWeBill** [comment]
There's a problem im experiencing now, The graph is taking the highest value of the first array and making it the maximum for the graph

**Comment by BrightonWeBill** [comment]
The graph is not accurate 
<img width="251" alt="screenshot 2018-11-29 at 15 31 55" src="https://user-images.githubusercontent.com/33026951/49225865-d28c2a00-f3ed-11e8-8e9a-076cf32a8382.png">

This is the dataset
<img width="293" alt="screenshot 2018-11-29 at 15 32 05" src="https://user-images.githubusercontent.com/33026951/49225911-edf73500-f3ed-11e8-914f-27394c05efae.png">

1st array is the red line,
2nd is the green line

**Comment by devcastoro** [comment]
The solution proposed by @Zazzzles seems a good one. Will you ever integrate this (fundamental) feature? @Hermanya

**Comment by Hermanya** [comment]
Thank you @devcastoro for reminding me, and @Zazzzles  for the initial design.
I expanded on this a little bit to allow for opacity to be consistent with the default values. The new api looks like this:
```
datasets: [{
    data: [ 20, 45, 28, 80, 99, 43 ],
    color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})` // optional
  }]
```
This is now avaiable for line chart in react-native-chart-kit@1.2.2
My apologies for the delay.

**Comment by flieks** [comment]
@Hermanya is multiple datasets also available for bar chart ?
we'd like to create this:
![image](https://user-images.githubusercontent.com/5032389/63208378-6fedd200-c0d3-11e9-9d46-caf0056a0478.png)

**Comment by Hermanya** [comment]
@flieks I don't think so, but I would welcome a PR

**Comment by ElixirMike** [comment]
If I wanted to change the colors of the bar chart and specify the color to use, could you provide where in the bar-chart.js  I would update the code to support this, just like you provided for the line chart?

**Comment by flieks** [comment]
@Hermanya maybe i'll do it, can you point me out where in the code (which class or function) this change would have to be implemented ?

**Comment by Hermanya** [comment]
@flieks here is the bar chart: https://github.com/indiespirit/react-native-chart-kit/blob/master/src/bar-chart.js

And here is the contribution guide: https://github.com/indiespirit/react-native-chart-kit/blob/master/contributing.md

**Comment by Technaur** [comment]
@Hermanya Is there a way to set the colour of the `fillShadowGradient` below the line graph?

**Comment by prajwalbhatia** [comment]
Can we change the color of different lines used in line chart through the solution given above without changing in node modules?

**Comment by Hermanya** [comment]
@prajwalbhatia no

**Comment by Rakeda** [comment]
> Can we change the color of different lines used in line chart through the solution given above without changing in node modules?

I was able to accomplish this by ensuring that the color parameter in the dataset was a function (lol?)

Example Dataset:


`<LineChart
                        data={{
                            datasets: [{
                                data: [
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100
                                ],
                                color: (opacity = 1) => 'rgba(58, 143, 255, 1)',
                                strokeWidth: 2 // optional
                            },
                            {
                                data: [
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100,
                                    Math.random() * 100
                                ],
                                color: (opacity = 1) => 'rgba(0, 255, 255, 1)',
                                strokeWidth: 2 // optional
                            }]
                        }}

chartConfig={{
                            backgroundColor: "transparent",
                            backgroundGradientFrom: '#ffffff00',
                            backgroundGradientTo: '#fff',
                            strokeWidth: 1,
                            decimalPlaces: 2, // optional, defaults to 2dp
                            color: (opacity = 1) => 'rgba(0, 255, 255, 1)'  //<- This is needed to prevent the color null from appearing
                        }}
/>`

**Comment by iamadityaaz** [comment]
This is the code which helped me to achieve the following Output :
Code : 
```
                             <LineChart
					bezier
					withHorizontalLabels={false}
					withVerticalLabels={false}
					data={{
						labels: [' 1', ' 2', ' 3', ' 4', ' 5', ' 6'],
						datasets: [
							{
								data: [1, 7, 6, 4, 2, 5],
								strokeWidth: 2,
								color: (opacity = 1) => `rgba(255,0,0,${opacity})`, // optional
							},
							{
								data: [2, 4, 6, 8, 8, 2],
								strokeWidth: 2,
								color: (opacity = 1) => `rgba(0,0,102, ${opacity})`, // optional
							},
							{
								data: [9, 4, 7, 8, 2, 4],
								strokeWidth: 2,
								color: (opacity = 1) => `rgba(0,102,0, ${opacity})`, // optional
							},
						],
						legend: ['Maths', 'SOM', 'DS'],
					}}
					width={Dimensions.get('window').width - 16}
					height={200}
					chartConfig={{
						backgroundColor: '#1cc910',
						backgroundGradientFrom: '#eff3ff',
						backgroundGradientTo: '#efefef',
						decimalPlaces: 2,
						color: (opacity = 1) => `rgba(0, 0, 0, ${opacity})`,
						style: {
							borderRadius: 16,
						},
					}}
					style={{
						marginVertical: 8,
						borderRadius: 16,
					}}
				/>
```

Output 

![image](https://user-images.githubusercontent.com/30999510/87045126-22abaf00-c215-11ea-81d5-d07369fd4d57.png)

**Comment by anupamhore** [comment]
Can we have multiple colors in the barchart. Right now it is not possible. I want to have something similar to the attached screenshot below
<img width="559" alt="Screenshot 2020-08-11 at 12 59 04 PM" src="https://user-images.githubusercontent.com/17607476/89858979-7a518780-dbd2-11ea-924f-3987babc03c1.png">

**Comment by amanfcp** [comment]
> Can we have multiple colors in the barchart. **Right now it is not possible**.
> 
> I want to have something similar to the attached screenshot below
> 
> <img alt="Screenshot 2020-08-11 at 12 59 04 PM" width="559" src="https://user-images.githubusercontent.com/17607476/89858979-7a518780-dbd2-11ea-924f-3987babc03c1.png">

Any update on this?

**Comment by giovanijfc** [comment]
> @Hermanya Existe uma maneira de definir a cor `fillShadowGradient`abaixo do gráfico de linha?

useShadowColorFromDataset defines the line color to ShadowGradient

**Comment by KawishAli6578** [comment]
is their anyway to change my legend color

**Comment by strongSoda** [comment]
> Thank you @devcastoro for reminding me, and @Zazzzles for the initial design. I expanded on this a little bit to allow for opacity to be consistent with the default values. The new api looks like this:
> 
> ```
> datasets: [{
>     data: [ 20, 45, 28, 80, 99, 43 ],
>     color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})` // optional
>   }]
> ```
> 
> This is now available for line chart in react-native-chart-kit@1.2.2 My apologies for the delay.

Hi @Hermanya, can we also similarly apply different colors to the dots for each dataset? If not any other way to do so?

I have 2 lines on the line-chart but only one has the end dot, and the other doesn't.
<img width="288" alt="Screenshot 2023-08-14 at 2 45 28 PM" src="https://github.com/indiespirit/react-native-chart-kit/assets/30754328/f7b9f8e5-1d5f-4d99-87c3-8f3a79cbd4bd">


How to apply the dot to the other line as well? And with different color?
