### ISSUE TITLE
withScrollableDot horizontal

### ISSUE THREAD

**Issue by binarygondola** [indiespirit/react-native-chart-kit#386]
I see in the source code an option for the `<LineChart />` titled `withScrollableDot`. Is it in the development stage or is it working? I couldn't find any example to showcase the usage of this feature.

Thanks for helping

**Comment by calirvine** [comment]
I'm also curious about this. If this is in a working state, it would save me a lot of work! I'll dig a bit into the source code and have a look, but if anyone has an answer I'd appreciate hearing it!

**Comment by aboveyunhai** [comment]
@binarygondola @calirvine I believe all examples are demonstrate inside `App.js`. Indeed it's a little bit hard to find,
https://github.com/indiespirit/react-native-chart-kit/blob/cb2d31e86fe40133cbf2a19f1453571998b8fe57/App.js#L244

**Comment by binarygondola** [comment]
After upgrading to the latest version, everything works fine, thanks @aboveyunhai
