### ISSUE TITLE
Remove vertical and horizontal lines in charts

### ISSUE THREAD

**Issue by Ivanrs297** [indiespirit/react-native-chart-kit#39]
Hi, how can I remove the vertical and horizontal lines of the grid?

Thank you !
![screen shot 2018-08-29 at 11 23 56 am](https://user-images.githubusercontent.com/26337972/44801192-08ffa200-ab7e-11e8-8750-92db845194db.png)

**Comment by Hermanya** [comment]
You'd have to modify the source code of this lib. If you do that, and make it configurable, make sure to open a Pull Request.

**Comment by tarunmehta-quovantis** [comment]
@Ivanrs297  did you achieve it, Did you modified code?
If yes, please let me know how to remove background lines

**Comment by Em01** [comment]
I know this is old but I was trying to figure out how to do this and it might be useful to someone. I was able to do this with the following:

      propsForBackgroundLines: {
        strokeWidth: 0
      }

**Comment by JBaczuk** [comment]
You can also use `withInnerLines={false}`

**Comment by SSOURABH58** [comment]
@Em01 and @jBaczuk can you pls tell me exactly how to remove the grid. in which block should I put the above code solu.

**Comment by JBaczuk** [comment]
@SSOURABH58 

For example:

```

<LineChart
  {...otherProps}
  withInnerLines={false}
/>
```

**Comment by atrocks01** [comment]
Hi @JBaczuk I want to remove only inner vertical lines is there any way to do this.

**Comment by FaisalKhawaj** [comment]
You can use this line in chartConfig 
`  backgroundGradientFrom: COLORS.WHITE.primary,
    backgroundGradientTo: COLORS.WHITE.primary,`

**Comment by Iyappan-mani** [comment]
use various 
```
<LineChart
  {...otherProps}
  withInnerLines={false}
               or
    // this use vertical line remove 
    withVerticalLines={false}
               or 
   // this use Horizontal line remove 
    withHorizontalLines={false}
/>
```
