### ISSUE TITLE
Bezier chart styling

### ISSUE THREAD

**Issue by orafaelfragoso** [indiespirit/react-native-chart-kit#406]
Hi guys,

This is not an issue in particular, but I haven't found a way to bend the chart style to my will yet.
I am trying to make something like this:

<img width="138" alt="Screen Shot 2020-09-16 at 15 48 14" src="https://user-images.githubusercontent.com/1163342/93379323-0ab76380-f834-11ea-9742-876d3791de1c.png">

No labels, borders, lines, legend or spaces...

This is what I have so far:

```javascript
<LineChart
      data={data}
      width={120}
      height={40}
      withDots={false}
      withInnerLines={false}
      withOuterLines={false}
      withVerticalLabels={false}
      withHorizontalLabels={false}
      yLabelsOffset={0}
      xLabelsOffset={0}
      chartConfig={{
        backgroundColor: '#FFF',
        backgroundGradientFrom: '#d3d',
        backgroundGradientTo: '#f3f',
        decimalPlaces: 2,
        color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
        labelColor: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
        style: {
          flex: 1,
          padding: 0,
          margin: 0,
        },
      }}
      bezier
    />
```

But I can't get rid of the spaces on the left or bottom. I also can't get the fill right for the lines. The documentation helped only up to a point.

Thanks.

**Comment by orafaelfragoso** [comment]
I couldn't reproduce this, due to the unnecessary padding inside the Chart. I ended up using a different library which gives me the option to remove all the padding and margins.

**Comment by xyaanz** [comment]
> I couldn't reproduce this, due to the unnecessary padding inside the Chart. I ended up using a different library which gives me the option to remove all the padding and margins.

hey bro, can you tell me which library you used?

**Comment by orafaelfragoso** [comment]
@xyaanz https://github.com/N1ghtly/react-native-responsive-linechart

**Comment by jeanniton-mnr** [comment]
> @xyaanz https://github.com/N1ghtly/react-native-responsive-linechart

I just reviewed this library.

I love it better than react-native-chart-kit. I will still use it, react native chart kit, for other chart such as the progress ring.


Thank you, and thank you again!
