### ISSUE TITLE
Can the charts be zoomed?

### ISSUE THREAD

**Issue by JungDonggun** [indiespirit/react-native-chart-kit#412]
Hi,

I would like to know if you eventually are going to offer the zoom feature for line charts, and if yes, do you have an idea of when?

**Comment by kdcaine** [comment]
Hi, no solution was found?

**Comment by JungDonggun** [comment]
@kdcaine  Yes but I'm using another library. https://github.com/wuxudong/react-native-charts-wrapper

**Comment by rassemdev** [comment]
@JungDonggun would you kindly share us a snack?
