### ISSUE TITLE
Creating Contribution Graph with only one value returns error

### ISSUE THREAD

**Issue by sinuheshinbr** [indiespirit/react-native-chart-kit#425]
If you create a contribution graph with only one date it will return: "rgba(255,82,82, NaN) is not a valid color. Probably due to the fact that opacity is compared with other values to be determined. In this case, I think it is possible to default count to 0 if no other record is provided.

**Comment by Andrew-Chen-Wang** [comment]
It's not just a single value. Using this data: `const contributionData = [{"count": 2, "date": "2021-07-31"}, {"count": 2, "date": "2021-08-01"}];` with an end date of '2021-08-03' also does not work and produces NaN. Anyone know how I could extend the current class to fix this issue temporarily?
