### ISSUE TITLE
BarChart Example not working on v6.7.0

### ISSUE THREAD

**Issue by NS-BOBBY-C** [indiespirit/react-native-chart-kit#433]
After release v6.7.0, a BarChart I was using has stopped working. I have provided a minimal repo with the issue here:

https://github.com/NS-BOBBY-C/RNChartKitIssue

Let me know if there is any more information you need me to provider to help resolve this issue!

Please let me know if this is a lapse in documentation - I will gladly update the documentation if someone points me in the right direction. Unfortunately, I do not have the time to fix the issue myself.

**Comment by alexpineda99** [comment]
I have the same issue.

**Comment by diogomfc** [comment]
Mesmo Problema. Algum retorno??

**Comment by qskeksq** [comment]
Check out pull-request #429

for BarChart, there should be 'data' attribute in chartConfig from release 6.7

after adding data, it worked for me

**Comment by alexpineda99** [comment]
> Check out pull-request #429
> 
> for BarChart, there should be 'data' attribute in chartConfig from release 6.7
> 
> after adding data, it worked for me

Amazing! It worked. Thanks bruh.

**Comment by NS-BOBBY-C** [comment]
Closing because it was fixed since I created this.
