### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by pavel-zlotarenchuk** [indiespirit/react-native-chart-kit#46]
When I try to import a library, I get an error

`Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.`

My project looks like this
```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Dimensions} from 'react-native';
import {
    LineChart,
    BarChart,
    PieChart,
    ProgressChart,
    ContributionGraph
} from 'react-native-chart-kit'


const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

Of course I did 
`yarn add react-native-chart-kit`

**Comment by pavel-zlotarenchuk** [comment]
> Same here. Looks like importing anything from react-native-chart-kit is enough to cause the error.

Yes
The project starts if delete this:
```
import {
    LineChart,
    BarChart,
    PieChart,
    ProgressChart,
    ContributionGraph
} from 'react-native-chart-kit'
```

**Comment by minzarddillah** [comment]
same here, please fix this

**Comment by Hatestorm** [comment]
+1

**Comment by lunadis** [comment]
+1

**Comment by oakfire** [comment]
Same with:
react-native 0.57.4
react-native-svg 8.0.8
react-native-chart-kit 1.1.9

**Comment by noluckjustskill** [comment]
> 
> 
> I found the solution to this problem.
> 1: Comment `import 'babel-polyfill'` from first line of [react-native-chart-kit](https://github.com/indiespirit/react-native-chart-kit/blob/master/index.js) index.js
> 
> 2: Install [react-native-svg](https://github.com/react-native-community/react-native-svg/blob/master/README.md#installation)
> 
> Edit:
> Also for pieChart, must added `import 'babel-polyfill';` into pie-chart.js

Worked! Thank you!

**Comment by JuanCamilo0809** [comment]
> I found the solution to this problem.
> 1: Comment `import 'babel-polyfill'` from first line of [react-native-chart-kit](https://github.com/indiespirit/react-native-chart-kit/blob/master/index.js) index.js
> 
> 2: Install [react-native-svg](https://github.com/react-native-community/react-native-svg/blob/master/README.md#installation)
> 
> Edit:
> Also for pieChart, must added `import 'babel-polyfill';` into pie-chart.js

Perfect!!! Thank you!!
