### ISSUE TITLE
Trying to remove a view index above the child Error.

### ISSUE THREAD

**Issue by dileepbolisetti** [indiespirit/react-native-chart-kit#49]
![screenshot_1538462381](https://user-images.githubusercontent.com/8918698/46332959-10621180-c63c-11e8-973a-0c7a72efd50c.png)

"react-native-chart-kit": "^1.1.7",
"react-native": "0.55.4",
"react-native-svg": "^7.0.3"

Even for the Example code is showing the same result.

**Comment by 3210jr** [comment]
Hey @dileepbolisetti , I am facing the same issue. Until it is resolved I am using the following patch:

For my line charts, i went to `/node_modules/react-native-chart-kit/src/line-chart.js` and wrapped everything inside the <Svg> tag with a <G> tag that I imported from the react-native-svg library.

`import { Svg, Circle, Polygon, Polyline, Path, Rect, G } from "react-native-svg";`

<img width="798" alt="screen shot 2018-10-02 at 12 02 04 pm" src="https://user-images.githubusercontent.com/11012023/46339322-27ecca80-c63b-11e8-8595-055314cbb664.png">

**Comment by IgnacioGall** [comment]
@3210jr 
Hello! Thanks for de answer!
i import this : 
`import { Svg, Circle, Polygon, Polyline, Path, Rect, G } from "react-native-svg";`
But now i have a similar error:
![screenshot_20181008-114302](https://user-images.githubusercontent.com/43962674/46615869-ae982080-caef-11e8-9052-41468e03abe8.png)

do you have any idea what the problem would be now?

Thanks anyway!

**Comment by Hermanya** [comment]
The PR #52 should have fixed this
