### ISSUE TITLE
PropsLabel, PropsHorizontalLabel, PropsVerticalLabel, these props override style is not working

### ISSUE THREAD

**Issue by SrinivasanJms** [indiespirit/react-native-chart-kit#493]
We can't add any styles for label, already there is proper called propsForLabel, propsForHorizontalLabel, and propsForVerticalLabel but nothing is working. please give me a solution. Thanks in advance

**Comment by AmitP1392** [comment]
Hi Team,
Using LineChart form the library.
here if you see, i am trying to modify the labels style for the x-axis label but padding style is not working. Could you please help out to resolve the issue.

```
const chartConfiguration = {
        backgroundGradientFrom: "#1C1F24",
        backgroundGradientFromOpacity: 1,
        backgroundGradientTo: "#1C1F24",
        backgroundGradientToOpacity: 1,
        fillShadowGradientOpacity: 1,
        fillShadowGradient: "#FFBF6D",
        propsForBackgroundLines: {
            strokeDasharray: "", // solid background lines with no dashes
            stroke: "#484847",
            strokeWidth: 1.5
        },
        color: (opacity = 1) => `#1C1F24`,
        labelColor: (opacity = 1) => `#D3D3D2`,
        propsForLabels: {
            fontSize: "14",
            fill: "rgba(10, 10, 10, 1)",
            fontWeight: 500,
            padding: 5
        },
        useShadowColorFromDataset: false
    };
```

<img width="246" alt="image" src="https://user-images.githubusercontent.com/117336223/199653252-c7a00de5-46be-4e1c-8c29-eea4e0acfddb.png">
