### ISSUE TITLE
Make line chart lines opacity configurable 

### ISSUE THREAD

**Issue by JakobHartman** [indiespirit/react-native-chart-kit#501]
line 325:  in linechart.js ` return (<Path key={index} d={result} fill="none" stroke={_this.getColor(dataset, 0.2)} strokeWidth={_this.getStrokeWidth(dataset)} strokeDasharray={dataset.strokeDashArray} strokeDashoffset={dataset.strokeDashOffset}/>`

looks like the opacity is hardcoded to 0.2 is it possible to make it configurable.

**Comment by SaltedBlowfish** [comment]
@JakobHartman I see what you're referring to in the source code: https://github.com/indiespirit/react-native-chart-kit/blob/master/src/line-chart/LineChart.tsx#L724

You can, however, specify the opacity of the line like the following:

```
<LineChart
  data={{
    labels: [
      'Jan',
      'Feb',
      'Mar',
     // ...
    ],
    datasets: [
      {
        data: [
          Math.floor(Math.random() * 100),
          Math.floor(Math.random() * 100),
          Math.floor(Math.random() * 100),
          // ...
        ],
        color: (opacity) => 'rgba(0, 0, 0, 0.1)', //       <----- HERE (0.1)
      },
    ],
  }}
  ...
/>
```

Adjusting that value yields the following opacity changes for me:

## Opacity of 0.1 - rgba(0, 0, 0, 0.1):
![image](https://user-images.githubusercontent.com/6200478/116724124-202d6800-a995-11eb-92d0-8b9f0e02da49.png)


## Opacity of 0.9 - rgba(0, 0, 0, 0.9)
![image](https://user-images.githubusercontent.com/6200478/116724160-2c192a00-a995-11eb-85d5-40f9f62d026f.png)


See documentation reference here: 
https://github.com/indiespirit/react-native-chart-kit#line-chart

```
const data = {
  labels: ["January", "February", "March", "April", "May", "June"],
  datasets: [
    {
      data: [20, 45, 28, 80, 99, 43],
      color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})`, // optional
      strokeWidth: 2 // optional
    }
  ],
  legend: ["Rainy Days"] // optional
};
```

**Comment by JakobHartman** [comment]
I do have it written like what it is in the example 

white = (opacity = 1) => `rgba(255, 255, 255, ${opacity})`;

data: [238, 238, 238, 238, 238, 238, 238],
      color: white,
      strokeWidth: 3,
    },
![Screen Shot 2021-05-05 at 12 54 07 PM](https://user-images.githubusercontent.com/5502660/117186932-fd3df200-ada0-11eb-93f6-2c3e1be957a2.png)

**Comment by JakobHartman** [comment]
![Screen Shot 2021-05-05 at 12 56 10 PM](https://user-images.githubusercontent.com/5502660/117187368-73425900-ada1-11eb-89c5-5985031f95bc.png)

This is what the color is supposed to be represented by the legend

**Comment by SaltedBlowfish** [comment]
Well, I'm not the maintainer of this repo. Was just trying to offer some help based on what worked for me. Good luck.

**Comment by JakobHartman** [comment]
I fixed it, does not like the (opacity = 1) => 'rgba(255, 255, 255, ${opacity})'; putting () => `rgba(255, 255, 255, 1)` that seemed to have fixed it

**Comment by SaltedBlowfish** [comment]
@JakobHartman Yep. Exactly what I was telling you to do. Glad you figured it out.
