### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string but got undefined.

### ISSUE THREAD

**Issue by tscans** [indiespirit/react-native-chart-kit#51]
I'm using the example on the github page with boilerplate react native expo snack code. The error only arises when I add the chartConfig prop (with the default chartConfig provided in the readme). I can't get the component to load on screen at all and consistently get this error.

**Comment by przywartya** [comment]
Same problem here :+1:  (example from README.md)

**Comment by Hermanya** [comment]
Here is a working example: https://github.com/indiespirit/react-native-chart-kit-example
