### ISSUE TITLE
Two-color gradient for fillShadowGradient in LineChart

### ISSUE THREAD

**Issue by ezrafree** [indiespirit/react-native-chart-kit#512]
I currently am using the `LineChart` component to build out an area chart, for example:

![image](https://user-images.githubusercontent.com/2496987/119905242-13a31d80-bf09-11eb-8c50-968585278789.png)

However, I need the linear gradient of `fillShadowGradient` to fade from one color to another. I see in [AbstractChart.tsx lines 479 through 484](https://github.com/indiespirit/react-native-chart-kit/blob/master/src/AbstractChart.tsx#L479-L484) that the `<Stop>` element is hard-coded to fade to `0`.

Is there a way I can extend the class from `AbstractChart` in my own project and override the `renderDefs()` method with my own? And if so, are there any code examples of this anywhere? Thanks in advance!

**Comment by johndpope** [comment]
<img width="504" alt="Screenshot 2024-01-04 at 2 01 01 pm" src="https://github.com/indiespirit/react-native-chart-kit/assets/289994/c850cf3a-8a1b-4d0e-b43e-3fb5e54cf3fd">


I need this too.

**Comment by cn-johndpope** [comment]
looking at example - 
  backgroundGradientFrom: "#1E2923",
    backgroundGradientTo: "#08130D",

maybe this helps.
