### ISSUE TITLE
Label color index not working

### ISSUE THREAD

**Issue by MoraesGil** [indiespirit/react-native-chart-kit#519]
I've try colorize Label by index as describe in documentation but index always come undefined, have another way to I set different colors for label??

` /**
     * Defines the base color function that is used to calculate colors of labels and sectors    used in a chart
     */
    color?: (opacity: number, index?: number) => string;`

![image](https://user-images.githubusercontent.com/7747175/120903545-0975d300-c61d-11eb-96be-840e7f5b79a8.png)

**Comment by gabrielew** [comment]
I have the same issue, do you fix it?

**Comment by MoraesGil** [comment]
Hi, @gabrielew is too long time ago over 13months from now however I remember this index doesn't works, I have just set an array with default color and else with  specific color, I'll share here. 
![image](https://user-images.githubusercontent.com/7747175/179520472-30c27ebe-4516-4353-bb7e-2a5e92cf01a2.png)
