### ISSUE TITLE
Bar position when all data is 0

### ISSUE THREAD

**Issue by daniel0128** [indiespirit/react-native-chart-kit#54]
When `data = [0, 0, 0, 0, 0, 0, 0]`
it shows like this:
<img width="363" alt="screen shot 2018-10-24 at 12 01 28 pm" src="https://user-images.githubusercontent.com/8462910/47448036-9d544280-d784-11e8-9508-d95635f54f40.png">
Is there a way to scale Y-axis as [0,1] so that all the 0 go to the base line?

**Comment by daniel0128** [comment]
the reason is there's a NAN resulting from "divided by 0"
`const barHeight = height / 4 * 3 * ((x - Math.min(...data)) / (Math.max(...data) - Math.min(...data)))`
when the minimum and maximum of data are same
https://github.com/indiespirit/react-native-chart-kit/blob/master/src/bar-chart.js#L15

**Comment by daniel0128** [comment]
PR:
https://github.com/indiespirit/react-native-chart-kit/pull/58

**Comment by Hermanya** [comment]
PR was merged
