### ISSUE TITLE
Right shift X Axis

### ISSUE THREAD

**Issue by tusharpandey** [indiespirit/react-native-chart-kit#552]
How can I shift X-Axis from left or provide some spacing from left.

<img width="436" alt="Screenshot 2021-09-07 at 3 47 29 PM" src="https://user-images.githubusercontent.com/4696846/132328561-abea2fe6-b3f3-4206-871f-a756047afdb3.png">

Right now I am able to draw graph like this.

![Screenshot_20210907-155040~2](https://user-images.githubusercontent.com/4696846/132329146-d98ff08b-baf3-4550-8d5d-cedd20d6c8ab.png)

can I provide space from left to X-Axis ( attaching my code )

`

    render() {

        let {
            data
        } = this.props

        return (<View style={{ flex: 1 }}>
            <LineChart
                barPercentage={undefined}
                withInnerLines={false}
                // fromZero={true}
                data={data}
                width={getDeviceWidth()}
                height={220}
                // hidePointsAtIndex={[0]}
                // hidePointsAtIndex={}
                chartConfig={{
                    fillShadowGradient: shadowColor,
                    fillShadowGradientOpacity: 1,
                    backgroundGradientFrom: graphBGColor,
                    backgroundGradientTo: graphBGColor,
                    color: () => markerLine,
                    strokeWidth: 2, // optional, default 3
                    barPercentage: 0.5,
                    propsForBackgroundLines: {
                        strokeWidth: 1,
                        strokeDasharray: "",
                    },
                }}
                style={{
                    backgroundColor: graphBGColor,
                }}
            />
        </View>)
    }
}
`

**Comment by tusharpandey** [comment]
to all who wants to shift it like above graph ... i am passing props to it (this.rightShiftGraph)

<img width="1224" alt="Screenshot 2021-09-11 at 7 59 07 AM" src="https://user-images.githubusercontent.com/4696846/132933250-f1c6a7e5-fee2-4529-bc3d-94eccb54c03b.png">

and to use it locally you can copy folder of **react-native-chart-kit** and paste into your local folder like I am putting it inside **external_moudles_folder** 

<img width="305" alt="Screenshot 2021-09-11 at 8 02 45 AM" src="https://user-images.githubusercontent.com/4696846/132933313-2b3f114c-afbc-4be0-abe5-25a844e17640.png">

and to use it in your app you can change your package json like this : 

<img width="529" alt="Screenshot 2021-09-11 at 8 03 38 AM" src="https://user-images.githubusercontent.com/4696846/132933341-51ee9175-2edb-4a1b-bfbc-e0ae50c56984.png">

**Comment by lnqminh3003** [comment]
nice approach
