### ISSUE TITLE
How can we remove grid at background in line graph

### ISSUE THREAD

**Issue by tarunmehta-quovantis** [indiespirit/react-native-chart-kit#57]
Is there any way to remove grid at background in line graph?

**Comment by mcabs3** [comment]
Currently no, but I can work on adding that pretty easily.

Alternatively, you can extend the `AbstractChart` and recreate your own LineChart

**Comment by tarunmehta-quovantis** [comment]
@mcabs3 , if possible please provide me such functionality(remove grid) asap. I will be really thankful for you   :)
and Thank you for providing such an awesome library.

**Comment by mcabs3** [comment]
@tarunmehta-quovantis if you are under time crunch, copy the `line-chart` file and put it in your project (update the imports to use the library), and remove 186 - 191, and 200 - 205.

**Comment by tarunmehta-quovantis** [comment]
@mcabs3 , thank you for your quick response, 
I did it but end up with error, Object.defineProperty called  on non-object, searched on google found error but couldn't solve it

**Comment by v-vashchenko** [comment]
withInnerLines={false}

**Comment by arvindkumarmeel** [comment]
Is there any way to remove grid at background in line graph?
