### ISSUE TITLE
Unable run demo to contribute

### ISSUE THREAD

**Issue by mcabs3** [indiespirit/react-native-chart-kit#59]
I am unable to get the library demo setup to run on a simulator so I can assist with some cleanup and features.

I installed dependencies, changed `main` in package.json, and tried running the app :/

**Comment by Hermanya** [comment]
😮 sorry about that
I cloned a fresh copy of this repo, and noticed that react-native-svg was missing from dev dependencies. I pushed a fix for that. Could you try again?

**Comment by mcabs3** [comment]
No worries, I just want to help!

I see two things that are problems

<img width="471" alt="screen shot 2018-11-05 at 1 55 01 pm" src="https://user-images.githubusercontent.com/1383910/48023232-cbca0a00-e102-11e8-8c95-0ccbf9576f52.png">

and 

![simulator screen shot - iphone x - 2018-11-05 at 13 56 05](https://user-images.githubusercontent.com/1383910/48023244-d4224500-e102-11e8-961e-08e354147c9c.png)

**Comment by mcabs3** [comment]
I figured it out, issue on my machine :) I'll start contributing! woot woot!

**Comment by Hermanya** [comment]
I get the first problem too, but it's quite expected. It happens because I don't want to lock react-native into a particular version, it's listed as a peer dependency. The packager works fine this way.
