### ISSUE TITLE
How can we give styling to the dot ?

### ISSUE THREAD

**Issue by ArchanaVasumathi** [indiespirit/react-native-chart-kit#616]
How can we give style to the dot to display like below?
<img width="57" alt="Screenshot 2022-06-20 at 9 49 32 PM" src="https://user-images.githubusercontent.com/106793180/174643931-45b2596c-6761-4152-80e3-aeb1bcb0e7f0.png">
w

**Comment by ghost** [comment]
@ArchanaVasumathi  do you know how to handle large dataset in linechart as its hangs the app

**Comment by ArchanaVasumathi** [comment]
Same issue duplicated  https://github.com/indiespirit/react-native-chart-kit/issues/617 , hence closed
