### ISSUE TITLE
Line Chart: many properties do not work in Expo

### ISSUE THREAD

**Issue by Jchang4** [indiespirit/react-native-chart-kit#659]
Many of the properties listed in the README for `LineChart` no longer work for some reason. A short list includes:

- fromZero
- segments
- withHorizontalLines
- withVeriticalLines

there's likely more props that do not work but I am giving up on this library until this is fixed since it can no longer fulfill my requirements.

**Comment by Jchang4** [comment]
its the expo-chart-kit package

**Comment by KMarkovskiy** [comment]
@Jchang4 , Did you find the reason? If yes, could you describe it here?
