### ISSUE TITLE
Remove dependency from expo

### ISSUE THREAD

**Issue by jarvisluong** [indiespirit/react-native-chart-kit#67]
Hi!

I can see from this package's ```package.json``` has ```expo@28.0.0``` as dependency. However it will conflict with newer expo since they use newer react-native-svg package (6.2.2 vs 8.0.8) and it will create an error ```Tried to register two views with the same name RNSVGPath```

**Comment by rodrix** [comment]
Hi, same problem here.
Following this issue. Thanks.

**Comment by gonzalovilaseca** [comment]
And here

**Comment by Hermanya** [comment]
Removed expo from dependencies, version 2.0.0 is up
