### ISSUE TITLE
Is there a way to add a custom background colour and data colour for each circle in the ProgressChart?

### ISSUE THREAD

**Issue by lovestaco** [indiespirit/react-native-chart-kit#684]
This is my graph data
```
{"background": ["#A7FFA7", "#EFEF8C", "#F39A9A"], "color": ["#007F14", "#9BB500", "#A20D00"], "data": [0.1, 0.1, 0.2], "labels": ["WELL-SPENT", "RECREATION", "UNPRODUCTIVE"]}
```

This is my ProgressChart
```
 const chartConfig = {
    backgroundGradientToOpacity: 0.5,
    color: (opacity = 1) => `rgba(26, 255, 146, ${opacity})`,
  };
 <ProgressChart
    data={graphData}
    height={220}
    width={300}
    chartConfig={chartConfig}
/>
```
        
![Selection_350](https://github.com/indiespirit/react-native-chart-kit/assets/66487268/cd690206-b3fe-4e13-928c-e9f3c3e43c15)

I tried this but it just fills in the colour and I'm not able to differentiate bw the background and data of the circle.
```
const chartConfig = {
    backgroundGradientToOpacity: 0.5,
   color: (opacity = 1, index) => graphData.color[index],
  };
```
   
  
![image](https://github.com/indiespirit/react-native-chart-kit/assets/66487268/cf29716a-da6b-423e-a8af-f6df73f0dabe)

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=m8gyy7JItmU https://www.youtube.com/watch?v=1WZjeESH4a0
