### ISSUE TITLE
Bug module also on expo

### ISSUE THREAD

**Issue by Angelk90** [indiespirit/react-native-chart-kit#69]
Hi @indiespirit, @Hermanya: 

I wanted to try the module but I could not try it if it was done by pc and on expo.

I have created an example expo link, to understand where I am wrong?

Link expo: https://snack.expo.io/rkXTF4-ZN

**Comment by Hermanya** [comment]
I could not figure out how to set up a snack properly, here is a github repo with a working example: https://github.com/indiespirit/react-native-chart-kit-example
