### ISSUE TITLE
Is it a way to make Line Chart with smooth animation ?

### ISSUE THREAD

**Issue by SBRKH** [indiespirit/react-native-chart-kit#696]
Hello,

I'm using the library to display line graphs but I'm not happy with the way the graph is displayed, so I tried displaying it "with animation".
To do this, instead of passing my datasets like this :
```
data={{
      labels: ["January", "February", "March", "April", "May", "June"],
      datasets: [
        {
          data: [
            Math.random() * 100,
            Math.random() * 100,
            Math.random() * 100,
            Math.random() * 100,
            Math.random() * 100,
            Math.random() * 100
          ]
        }
      ]
    }}

```
I'm doing like that : 
```
const [data, setData] = useState<number[]>([0]);

useInterval(() => {
setData(prev => ([...prev, Math.random() * 100]));
}, 250);

data={{
      labels: ["January", "February", "March", "April", "May", "June"],
      datasets: [
        {
          data
  }
      ]
    }}
```

It works but it's not smooth, it's like adding a dot directly onto the graphic without any fading or other animation...
I can't find a way to make it more smooth, does anyone have an idea?

Thank you for your help,

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=m8gyy7JItmU https://www.youtube.com/watch?v=1WZjeESH4a0
