### ISSUE TITLE
Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by jdpagley** [indiespirit/react-native-chart-kit#73]
When you already have react-native-svg as a dependency this error happens. As work around ,I removed react-native-svg from chart-kit node_module folder and the error goes away.

Could we possibly make `react-native-svg` as a peer dependency?

I'm currently using version: `1.2.2` of chart kit

**Comment by Hermanya** [comment]
`react-native-svg` is already a peer dependency, I think `expo` comes with its own `react-native-svg`, maybe we should make `expo` a peer dependency as well

**Comment by Hermanya** [comment]
I updated devs, react-native-chart-kit@2.0.0 is now available.

**Comment by sebestenyb** [comment]
I still have the same issue with (just with `RNSVGRect`)
```
    "expo": "^32.0.2",
...
    "react-native-chart-kit": "^2.4.0",
```

Did the update fix the problem for you @jdpagley ?

Thanks, Sebi
