### ISSUE TITLE
 Error while updating property 'strokeWidth' in shadow node of type: RNSVGPath

### ISSUE THREAD

**Issue by webguru103** [indiespirit/react-native-chart-kit#8]
I get an this error when the bezierLineChart is rendered.
I created the chart like the example.

Here is my react-native version
react-native: 0.54.0
react-native-chart-kit: 0.1.5
expo: 26.0.0

Can I get some help?

**Comment by marcelek** [comment]
Me too. Android only. iOS just crashes expo.app

**Comment by themakerman** [comment]
i thought of using this library on production. :(. I am facing the same error.

**Comment by Hermanya** [comment]
I created [an example app](https://github.com/indiespirit/react-native-chart-kit-example), that should work with the latest version of this library and other dependencies. Let me know if this issue persists.
