### ISSUE TITLE
Pie chart not display with 100% percentage

### ISSUE THREAD

**Issue by mvanvu** [indiespirit/react-native-chart-kit#89]
See the screenshot
![Selection_001](https://user-images.githubusercontent.com/5796168/54658083-6b11fb80-4afe-11e9-917c-9561fe291f8e.png)

**Comment by sarthakmis** [comment]
Same issue here also

**Comment by Hermanya** [comment]
This looks like a bug, that should be easy to fix.

**Comment by salmanLee** [comment]
any progress？

**Comment by thelumiereguy** [comment]
Any Progress so far? I'm facing the same issue as well

**Comment by AngelD218** [comment]
Any Progress so far? I'm facing the same issue as well x2

**Comment by NickyDo** [comment]
how to fix that @@, I'm facing the same issue as well x3 :((
