### ISSUE TITLE
simulator crash with latest version of Expo

### ISSUE THREAD

**Issue by violabg** [indiespirit/react-native-chart-kit#9]
I'm using:

```
"expo": "^26.0.0",
"react": "16.3.0",
"react-native": "~0.54.1",
```

and when I test it the iOS simulator crashes, I'm using your example code as source.
can you confirm that it should work, with the above configuration?

Thanks

**Comment by KGSachinthaU** [comment]
Me too

**Comment by marcelek** [comment]
Me too

**Comment by MobileAppVault** [comment]
**short update**

Upgrading to expo 27.0.0 doesn't work as well. 

I've also removed the node_modules folder and running `yarn` again. Nothing works :(

**Comment by sftgf** [comment]
I'm facing the same issue. Any update on this?
