### ISSUE TITLE
How to hide Y-axis label and shadow line

### ISSUE THREAD

**Issue by azui007** [indiespirit/react-native-chart-kit#90]
Hello Hermanya,
I use the LineChart,It looks like this.
![微信图片_20190320164211](https://user-images.githubusercontent.com/9415011/54670881-9c56ef80-4b2f-11e9-8936-61d8b0917214.png)
Code:

>      <LineChart
              data={{
                        labels: ['01', '02', '03', '04'],
                        datasets: [{
                            data: [
                                Math.random() * 100,
                                Math.random() * 100,
                                Math.random() * 100,
                                Math.random() * 100
                            ],
                            color: (opacity = 1) => `rgba(19, 155, 255, ${opacity})`
                        }]
                    }}
                    width={Dimensions.get('window').width} // from react-native
                    height={220}
                    withShadow={false}
                    withOuterLines={false}
                    chartConfig={{
                        withShadow: false,
                        withOuterLines: false,
                        backgroundColor: '#fff',
                        backgroundGradientFrom: '#fff',
                        backgroundGradientTo: '#fff',
                        decimalPlaces: 2, // optional, defaults to 2dp
                        color: (opacity = 1) => `rgba(90, 90, 90, ${opacity})`,
                        style: {
                            borderRadius: 16
                        }
                    }}
                    bezier
                    style={{
                        marginVertical: 8,
                        borderRadius: 16
                    }}
                />

I want to hide Y-axis label and shadow line,like this (tootip is not belong to chart)
![微信图片_20190320165125](https://user-images.githubusercontent.com/9415011/54671222-70883980-4b30-11e9-9b0b-cc81be7aaf86.png)
can you help me

**Comment by canpoyrazoglu** [comment]
Did you find a solution? I need exactly the same thing: to hide labels completely.

**Comment by Hermanya** [comment]
There is no out of the box solution for this, but I would welcome a PR.

**Comment by i1990jain** [comment]
you can use withHorizontalLabels={false} as a property to your LineChart element

**Comment by OskarJuszczyk** [comment]
withHorizontalLabels={false} is not working with StackedBarChart

**Comment by zanona** [comment]
`withHorizontalLabels={false}` works on `LineChart` however it still leaves an empty space to the left of the chart. Ideally, disabling it, would also extend the chart to use the entire available width.

**Comment by connoremma** [comment]
@azui007 @zanona 

Hey guys, taking a look at the source, there is a default paddingRight of 64 if it is not provided in the style prop. So you can set `paddingRight` to 0 explicitly to get your expected result. I ran into this same problem just now, here's my graph: 

![image](https://user-images.githubusercontent.com/17773699/92310692-c6e47480-ef7e-11ea-968f-48f0fc0ae4cb.png)


And the code: 
```
<Linechart
..some props
style={{ paddingRight: 0 }}
/>
```

**Comment by JoeMartin2001** [comment]
```
options={
   scales: {
     y: {
           display: false,
         },
     },
}
```
This did the trick for me

**Comment by dutarares08** [comment]
If anyone still need an answer:

<LineChart
  data={data}
  width={width}
  height={height}
  chartConfig={chartConfig}

  withInnerLines={false}  // hide the grid behind chart
  withHorizontalLabels={false} // hide horizontal labels
  withOuterLines={false} // hide lines next to labels
/>

This is what worked for me!

**Comment by hajun-myoung** [comment]
> @azui007 @zanona
> 
> Hey guys, taking a look at the source, there is a default paddingRight of 64 if it is not provided in the style prop. So you can set `paddingRight` to 0 explicitly to get your expected result. I ran into this same problem just now, here's my graph:
> 
> ![image](https://user-images.githubusercontent.com/17773699/92310692-c6e47480-ef7e-11ea-968f-48f0fc0ae4cb.png)
> 
> And the code:
> 
> ```
> <Linechart
> ..some props
> style={{ paddingRight: 0 }}
> />
> ```

Awsome! How did you find it???

**Comment by TalhaAbid1** [comment]
## I have A solution To Set *Y axis*  **LIMITS** And *Hide* There Pointers
![WhatsApp Image 2023-02-10 at 8 26 27 PM](https://user-images.githubusercontent.com/97280141/218129878-90afc0c6-3c0b-4894-9845-f7d59e20c7b3.jpeg)

<LineChart
              data={{
                labels: xAxis,
                datasets: [
                  {
                    data: yAxis,
                  },
                  {
                    data:[0],  // Set Min
                    withDots: false,
                  },
                  {
                    data:[10],   // Set MAX
                    withDots: false,
                  }
                ]
              }}

**Comment by ChristopherGroe1014** [comment]
![image](https://github.com/indiespirit/react-native-chart-kit/assets/97300146/f1dc278a-00ab-44d6-910a-ad52fe7e780a)

<LineChart
  data={{
      labels: [],
      datasets: [
          {
              data: [
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100,
                  Math.random() * 100
              ]
          }
      ]
  }}
  withHorizontalLabels={false}
  withVerticalLabels={false}
  withVerticalLines={false}
  withInnerLines={false}
  // withHorizontalLines={false}
  width={Dimensions.get("window").width} // from react-native
  height={200}
  yAxisLabel="$"
  // yAxisSuffix="k"
  yAxisInterval={1} // optional, defaults to 1
  chartConfig={{
      backgroundColor: "transparent",
      backgroundGradientFrom: "white",
      backgroundGradientTo: "white",
      backgroundGradientFromOpacity: 0,
      backgroundGradientToOpacity: 0,
      decimalPlaces: 2, // optional, defaults to 2dp
      color: (opacity = 1) => `rgba(33,150,83, ${opacity})`,
      labelColor: () => `rgba(33,150,83, ${0})`,
      style: {
          borderRadius: 16,
      },
      propsForDots: {
          r: "0",
          strokeWidth: "1",
          stroke: "#ffa726"
      }
  }}
  // bezier
  style={{
      marginVertical: 0,
      borderRadius: 0,
      borderColor:'red',
      borderWidth: 1,
  }}
/>

I am using this code now.
But as you can see on this image, I can not remove padding right and left.
I think xLabel and yLabel width is remained still.
